services:
  elasticsearch:
    container_name: serilog-elastic
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.23
    ports:
      - 9200:9200
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
    networks:
      - elastic

  kibana:
    container_name: serilog-elastic-kibana
    image: docker.elastic.co/kibana/kibana:7.17.23
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
    networks:
      - elastic

networks:
  elastic:
    driver: bridge

